### ISSUE TITLE
How to fix the ImportError?

### ISSUE THREAD

**Issue by weiyu-Liu** [DerryHub/BEVFormer_tensorrt#2]
When I use `sh samples/bevformer/base/pth2onnx.sh -d 0`,
get error:
`ImportError: cannot import name 'iou3d_cuda' from partially initialized module 'third_party.bevformer.ops.iou3d' (most likely due to a circular import) (/workspace/BEVFormer_tensorrt/./third_party/bevformer/ops/iou3d/__init__.py)`
Thx

**Comment by DerryHub** [comment]
It seems that the ops in `third_party/bevformer` have not been installed.
Did you run the following lines?
```shell
cd ${PROJECT_DIR}/third_party/bevformer
python setup.py build develop
```
