### ISSUE TITLE
Process finished with exit code 136 (interrupted by signal 8: SIGFPE)

### ISSUE THREAD

**Issue by lfs119** [DerryHub/BEVFormer_tensorrt#21]
Thanks for your owesome work and There some problems when i try to run samples/bevformer/plugin/tiny/onnx2trt.sh with 2080Ti
![image](https://user-images.githubusercontent.com/23014201/217981873-86b99514-64d5-4f57-89f0-45adab0df811.png)

**Comment by DerryHub** [comment]
Please provide your environments like PyTorch, coda, onnx, tensorrt versions.

**Comment by lfs119** [comment]
TensorRT-8.4.3.1     onnx==1.8.0   torch==1.12.0+cu116

**Comment by lfs119** [comment]
sh samples/bevformer/plugin/tiny/pth2onnx.sh
 bevformer_tiny_epoch_24_cp.onnx 链接     
  链接: https://pan.baidu.com/s/1Q0x1p7_Nh3LItqdkDIx9rQ  密码: b0su

**Comment by lfs119** [comment]
if I change onnx version to 1.7.0, just like your bevformer_tiny_epoch_24_cp.onnx, it works.

**Comment by DerryHub** [comment]
Glad to here that! BTW, my onnx version is 1.12.0 and pytorch version is 1.12.1+cu116.

**Comment by lfs119** [comment]
![image](https://user-images.githubusercontent.com/23014201/218064181-13a07ced-5d14-446c-9cc2-9a3c4c04e215.png)


Do you meet this warning when running  samples/bevformer/plugin/tiny/pth2onnx.sh
I think it's the reason of core dumped

**Comment by DerryHub** [comment]
Yes, this warning appears many times, but it dose not affect the model transformation.
