### ISSUE TITLE
could you please share BEFormer_tiny onnx model?

### ISSUE THREAD

**Issue by RunnerZhong** [DerryHub/BEVFormer_tensorrt#22]
I want to evaluate the model, onnx model is the best choice, thanks~

**Comment by DerryHub** [comment]
Sorry, this onnx model relies on some special operator plugins. But these plugins are not implemented on onnxruntime. Therefore, this onnx model can only be used as an intermediate model for the tensorrt engine.

**Comment by RunnerZhong** [comment]
got it, thanks your reply, could you help share it just for reference?

**Comment by DerryHub** [comment]
[bevformer_tiny_epoch_24_cp.onnx](https://drive.google.com/file/d/1FRQjC8zs8pXTIJUPHLv5sKa1rY8x47_N/view?usp=share_link)

**Comment by RunnerZhong** [comment]
Thanks a lot for your sharing ~~
