### ISSUE TITLE
Why pth_evaluate.sh use bevformer_base_trt.py config

### ISSUE THREAD

**Issue by WYYAHYT** [DerryHub/BEVFormer_tensorrt#24]
Hi,  I see that `bevformer_base_trt.py` is used for `pth_evaluate.sh` and `trt_evaluate.sh` in samples, I just wonder whther `bevformer_base.py` should be used in `pth_evaluate.sh`. 

Thanks for your great job!

**Comment by DerryHub** [comment]
There are a lot of operators that does not support ONNX or TensorRT in the original forward. The `pth_evaluate.sh` aims to verify that the revised `forward_trt` is consistent with the original accuracy.

**Comment by WYYAHYT** [comment]
Got it! Thanks a lot!
