### ISSUE TITLE
A runtimeerror was encountered while converting the model to onnx

### ISSUE THREAD

**Issue by weiyu-Liu** [DerryHub/BEVFormer_tensorrt#3]
Hello,
When I use `sh samples/bevformer/base/pth2onnx.sh -d 0`, I got a runtime error:

`RuntimeError: CUDA out of memory. Tried to allocate 236.00 MiB (GPU 0; 9.78 GiB total capacity; 8.04 GiB already allocated; 82.31 MiB free; 8.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Looks like enough memory, and I use RTX 3080.
Do I need to switch to a graphics card with more memory?
Thx.

**Comment by DerryHub** [comment]
You can modify the `pth2onnx.sh` file and remove `--cuda`. It will run on CPU instead of GPU.
By the way, I recommend you to convert with custom plugins to save much memory.

**Comment by yhwang-hub** [comment]
how do i use custom plugins  to convert？

**Comment by DerryHub** [comment]
Run the scripts in `samples/bevformer/plugin`. See README.md.
