### ISSUE TITLE
Install project error

### ISSUE THREAD

**Issue by HerrYu123** [DerryHub/BEVFormer_tensorrt#35]
Hello, thanks for your great work.
When I install this project, I meet the following errors during 'make -j$(nproc)'
```
/root/BEVFormer_tensorrt/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu(883): error: expression must be a modifiable lvalue                                                                 detected during instantiation of "void ms_deformable_im2col_cuda_int8(const int8_4 *, float, const int32_t *, const T *, const int8_t *, float, const int8_t *, float, int, int, int, int, int, int, i$t, int, int8_4 *, float, cudaStream_t) [with T=float]"                                                                                                                                                           (965): here

1 error detected in the compilation of "/root/BEVFormer_tensorrt/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu".
CMakeFiles/tensorrt_ops.dir/build.make:159: recipe for target 'CMakeFiles/tensorrt_ops.dir/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu.o' failed
make[2]: *** [CMakeFiles/tensorrt_ops.dir/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by HerrYu123** [comment]
My environment:
Tensorrt 8.5.1.7
cudnn 8.5.0
CUDA-11.4
Thanks in advance

**Comment by DerryHub** [comment]
https://github.com/DerryHub/BEVFormer_tensorrt/blob/2a5fa0a2f66ac70859443a7490bd8dd9ccf5a500/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu#L873-L909

The `channels` is not a `const int` and should be a modifiable lvalue. I think this is maybe due to a version issue with mvcc. You can try to modify `const int channels` to `int channels` of  the head file `TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.h` 
https://github.com/DerryHub/BEVFormer_tensorrt/blob/2a5fa0a2f66ac70859443a7490bd8dd9ccf5a500/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.h#L35

**Comment by TGpastor** [comment]
> https://github.com/DerryHub/BEVFormer_tensorrt/blob/2a5fa0a2f66ac70859443a7490bd8dd9ccf5a500/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu#L873-L909
> 
> 这`channels`不是并且`const int`应该是可修改的左值。我认为这可能是由于 mvcc 的版本问题。可以尝试修改头文件的`const int channels`to`int channels``TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.h`
> 
> https://github.com/DerryHub/BEVFormer_tensorrt/blob/2a5fa0a2f66ac70859443a7490bd8dd9ccf5a500/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.h#L35

thanks, it works, but when I try to use"sh samples/test_trt_ops.sh",I meet the error"No module named 'pytorch_quantization",did I missed some steps?

**Comment by DerryHub** [comment]
see https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization

**Comment by TGpastor** [comment]
> see https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization

Thank you ,though all the result of "test_trt_ops.sh" are "Fail",  I still managed to finished the convert of model. Now all I need to do is to buy a 3060.(when I try to evaluate the trt model,it says " CUDA error: no kernel image is available for execution on the device",I guess my 2080ti doesn't match with pytorch1.12) Any way, thank you for your great job,hope you have a nice day.

**Comment by DerryHub** [comment]
Glad to hear that! But it works on my 2080ti with pytorch1.12.1+cu116. I recommend using the environment in README.


> > see https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization
> 
> Thank you ,though all the result of "test_trt_ops.sh" are "Fail", I still managed to finished the convert of model. Now all I need to do is to buy a 3060.(when I try to evaluate the trt model,it says " CUDA error: no kernel image is available for execution on the device",I guess my 2080ti doesn't match with pytorch1.12) Any way, thank you for your great job,hope you have a nice day.

**Comment by TGpastor** [comment]
> Glad to hear that! But it works on my 2080ti with pytorch1.12.1+cu116. I recommend using the environment in README.
> 
> > > see https://github.com/NVIDIA/TensorRT/tree/main/tools/pytorch-quantization
> > 
> > 
> > Thank you ,though all the result of "test_trt_ops.sh" are "Fail", I still managed to finished the convert of model. Now all I need to do is to buy a 3060.(when I try to evaluate the trt model,it says " CUDA error: no kernel image is available for execution on the device",I guess my 2080ti doesn't match with pytorch1.12) Any way, thank you for your great job,hope you have a nice day.

That's strange,the version of my cuda is 11.3, I think there's nothing with my pytorch and cuda, so what could lead to this?

the error message: 
`
Cuda failure /root/autodl-tmp/BEVFormer_tensorrt/TensorRT/plugin/modulated_deformable_conv2d/modulatedDeformableConv2dKernel.cu:610: 'no kernel image is available for execution on the device'
-------------------------------------------------------------------
PyCUDA ERROR: The context stack was not empty upon module cleanup.
-------------------------------------------------------------------
A context was still active when the context stack was being
cleaned up. At this point in our execution, CUDA may already
have been deinitialized, so there is no way we can finish
cleanly. The program will be aborted now.
Use Context.pop() to avoid this problem.
-------------------------------------------------------------------
`

**Comment by HerrYu123** [comment]
> https://github.com/DerryHub/BEVFormer_tensorrt/blob/2a5fa0a2f66ac70859443a7490bd8dd9ccf5a500/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu#L873-L909
> 
> The `channels` is not a `const int` and should be a modifiable lvalue. I think this is maybe due to a version issue with mvcc. You can try to modify `const int channels` to `int channels` of the head file `TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.h`
> 
> https://github.com/DerryHub/BEVFormer_tensorrt/blob/2a5fa0a2f66ac70859443a7490bd8dd9ccf5a500/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.h#L35

It works! But I get another error when I run the script 'sh samples/bevformer/base/pth2onnx.sh -d 0'.
···
Traceback (most recent call last):
  File "tools/pth2onnx.py", line 59, in <module>
    main()
  File "tools/pth2onnx.py", line 48, in main
    pytorch2onnx(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/BEVFormer_tensorrt/./det2trt/convert/pytorch2onnx.py", line 45, in pytorch2onnx
    torch.onnx.export(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 223, in _optimize_graph
    torch._C._jit_pass_onnx_graph_shape_type_inference(graph, params_dict, _export_onnx_opset_version)
RuntimeError: unexpected tensor scalar type
···
My environment:
torch 1.9.0
onnx 1.12.0
Thanks a lot!

**Comment by DerryHub** [comment]
> > https://github.com/DerryHub/BEVFormer_tensorrt/blob/2a5fa0a2f66ac70859443a7490bd8dd9ccf5a500/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu#L873-L909
> > 
> > The `channels` is not a `const int` and should be a modifiable lvalue. I think this is maybe due to a version issue with mvcc. You can try to modify `const int channels` to `int channels` of the head file `TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.h`
> > https://github.com/DerryHub/BEVFormer_tensorrt/blob/2a5fa0a2f66ac70859443a7490bd8dd9ccf5a500/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.h#L35
> 
> It works! But I get another error when I run the script 'sh samples/bevformer/base/pth2onnx.sh -d 0'.
> 
> ```
> Traceback (most recent call last):
>   File "tools/pth2onnx.py", line 59, in <module>
>     main()
>   File "tools/pth2onnx.py", line 48, in main
>     pytorch2onnx(
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "/root/autodl-tmp/BEVFormer_tensorrt/./det2trt/convert/pytorch2onnx.py", line 45, in pytorch2onnx
>     torch.onnx.export(
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
>     return utils.export(model, args, f, export_params, verbose, training,
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
>     _export(model, args, f, export_params, verbose, training, input_names, output_names,
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
>     _model_to_graph(model, args, verbose, input_names,
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 463, in _model_to_graph
>     graph = _optimize_graph(graph, operator_export_type,
>   File "/root/miniconda3/lib/python3.8/site-packages/torch/onnx/utils.py", line 223, in _optimize_graph
>     torch._C._jit_pass_onnx_graph_shape_type_inference(graph, params_dict, _export_onnx_opset_version)
> RuntimeError: unexpected tensor scalar type
> ```
> 
> My environment: torch 1.9.0 onnx 1.12.0 Thanks a lot!

Please update your pytorch to 1.12.1
