### ISSUE TITLE
cannot import name 'iou3d_cuda' from partially initialized module 'third_party.bevformer.ops.iou3d' 

### ISSUE THREAD

**Issue by yhwang-hub** [DerryHub/BEVFormer_tensorrt#4]
ImportError: cannot import name 'iou3d_cuda' from partially initialized module 'third_party.bevformer.ops.iou3d' (most likely due to a circular import) (/home/wyh/BEVFormer_tensorrt/third_party/bevformer/ops/iou3d/__init__.py)
请问这个问题该怎样解决？

**Comment by DerryHub** [comment]
See #2

**Comment by yhwang-hub** [comment]
thank you!
