### ISSUE TITLE
Dockerfile for installing the project.

### ISSUE THREAD

**Issue by matcosta23** [DerryHub/BEVFormer_tensorrt#43]
Would you have a Dockerfile with all the installations to be done? I'm having some issues for running the project. Thank you.

**Comment by DerryHub** [comment]
Sorry, there is no dockerfile in this project. You can tell the issues maybe I can help you.

**Comment by matcosta23** [comment]
Thanks for your quick answer. I was making some mistakes when installing the environment. Later on I kind of created a Dockerfile, but it's not 100% functional yet. If I finish it, I can do a pull request if you'd like to. Thanks again!
