### ISSUE TITLE
Error executing samples/test_trt_ops.sh

### ISSUE THREAD

**Issue by sun-lingyu** [DerryHub/BEVFormer_tensorrt#47]
Hi, I got this output when executing sh samples/test_trt_ops.sh. I noticed that I was using pytorch 1.11, so I upgraded to pytorch 1.12.0. However, this error remains. Any ideas? Thank you!

```Running on the GPU: 0
Loaded tensorrt plugins from /home/sly/NEXT/BEVFormer_tensorrt/TensorRT/lib/libtensorrt_ops.so
WARNING: Logging before flag parsing goes to stderr.
W0424 21:00:52.183286 281473776302240 collision.py:11] No FCL -- collision checking will not work

#################### Running GridSampler2DTestCase ####################
test_fp16_bicubic_border_NoAlignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... /home/sly/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/onnx/utils.py:294: UserWarning: `add_node_names' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `add_node_names` argument will be ignored.
  warnings.warn("`{}' can be set to True only when 'operator_export_type' is "
/home/sly/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/onnx/utils.py:294: UserWarning: `do_constant_folding' can be set to True only when 'operator_export_type' is `ONNX`. Since 'operator_export_type' is not set to 'ONNX', `do_constant_folding` argument will be ignored.
  warnings.warn("`{}' can be set to True only when 'operator_export_type' is "
/home/sly/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/nn/modules/module.py:1402: UserWarning: positional arguments and argument "destination" are deprecated. nn.Module.state_dict will not accept them in the future. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
/home/sly/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/tensorrt/__init__.py:75: DeprecationWarning: Context managers for TensorRT types are deprecated. Memory will be freed automatically when the reference count reaches 0.
  warnings.warn(
ERROR
test_fp16_bicubic_border_alignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
test_fp16_bicubic_reflection_NoAlignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
test_fp16_bicubic_reflection_alignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
test_fp16_bicubic_zeros_NoAlignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
test_fp16_bicubic_zeros_alignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
test_fp16_bilinear_border_NoAlignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
test_fp16_bilinear_border_alignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
test_fp16_bilinear_reflection_NoAlignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
test_fp16_bilinear_reflection_alignCorners (det2trt.models.utils.test_trt_ops.test_grid_sampler.GridSampler2DTestCase) ... ERROR
(Omitted)```

**Comment by sun-lingyu** [comment]
[verbose.log](https://github.com/DerryHub/BEVFormer_tensorrt/files/11310830/verbose.log)
Detailed output attached when setting ```TRT_LOGGER = trt.Logger(trt.Logger.VERBOSE)```

**Comment by sun-lingyu** [comment]
Resolved. 

The problem lies in TensorRT and is not related to Pytorch. I was using TensorRT 8.4, which does not have `tensorrt.tensorrt.ICudaEngine.get_tensor_mode()` and `tensorrt.tensorrt.ICudaEngine.get_tensor_dtype()` functions. The reason why there is only an "ERROR" message shown in verbose.log is that samples/test_trt_ops.sh uses unittest python module, and it hides the error message given by TensorRT.

To fix this problem, the simplest way is to update TensorRT version to the recommended one. 

However, I was using a Jetson Orin board whose TensorRT version cannot be updated directly. So I modified det2trt/models/utils/test_trt_ops/utils.py, replacing the two functions by legacy ones: `tensorrt.tensorrt.ICudaEngine.binding_is_input()` and `tensorrt.tensorrt.ICudaEngine.get_binding_dtype()`. Detailed description of the functions can be found [here](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Engine.html).

**Comment by Alex-fishred** [comment]
gine.html)找到。
> 解決。
> 
> 問題出在TensorRT上，與Pytorch無關。我使用的是TensorRT 8.4，它沒有`tensorrt.tensorrt.ICudaEngine.get_tensor_mode()`功能`tensorrt.tensorrt.ICudaEngine.get_tensor_dtype()`。verbose.log中只顯示「ERROR」訊息的原因是samples/test_trt_ops.sh使用了unittest python模組，並且隱藏了它了TensorRT給出了錯誤訊息。
> 
> 要解決此問題，最簡單的方法只需將 TensorRT 版本更新為建議版本。
> 
> 但是，我使用的是 Jetson Orin 板，其 TensorRT 版本無法直接更新。所以我修改了 det2trt/models/utils/test_trt_ops/utils.py，用舊函數替換了兩個函數：`tensorrt.tensorrt.ICudaEngine.binding_is_input()`和`tensorrt.tensorrt.ICudaEngine.get_binding_dtype()`。功能的詳細描述可以[在這裡](https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Engine.html)找到。

Thanks for your solution，Let me add the complete solution
After replacing the function, you must also make changes to the if function
#if engine.get_tensor_mode(binding) == trt.TensorIOMode.INPUT: 
if engine.binding_is_input(binding): 
     dims = input_shapes[binding] 
#elif engine.get_tensor_mode(binding) == trt.TensorIOMode.OUTPUT: 
else : 
     dims = output_shapes[binding] 

#dtype = trt.nptype(engine.get_tensor_dtype(binding)) 
dtype = trt.nptype(engine.get_binding_dtype(binding))

#if engine.get_tensor_mode(binding) == trt.TensorIOMode.INPUT:
if engine.binding_is_input(binding): 
          inputs.append(HostDeviceMem(binding, host_mem, device_mem))
else:
         outputs.append(HostDeviceMem(binding, host_mem, device_mem))
