### ISSUE TITLE
ImportError: cannot import name 'iou3d_cuda' from partially initialized module 'third_party.bev_mmdet3d.ops.iou3d'

### ISSUE THREAD

**Issue by Ashu683** [DerryHub/BEVFormer_tensorrt#52]
ImportError: cannot import name 'iou3d_cuda' from partially initialized module 'third_party.bev_mmdet3d.ops.iou3d' (most likely due to a circular import) (/workspace/BEVFormer_tensorrt/./third_party/bev_mmdet3d/ops/iou3d/__init__.py)

**Comment by DerryHub** [comment]
see #2
