### ISSUE TITLE
what's the difference between mmdeploy plugins and custom plugins ?

### ISSUE THREAD

**Issue by reverse-2020** [DerryHub/BEVFormer_tensorrt#68]
i find theri onnx is different , mmdeploy plugins seems not have the op MultiScaleDeformableAttnTRT ,how does it works？

**Comment by DerryHub** [comment]
MultiScaleDeformableAttnTRT(2) support half(half2)/int8 while the mmdeploy plugins don't support. You can refer https://github.com/DerryHub/BEVFormer_tensorrt/tree/main/TensorRT#multi-scale-deformable-attention to use it.

**Comment by reverse-2020** [comment]
> MultiScaleDeformableAttnTRT(2) support half(half2)/int8 while the mmdeploy plugins don't support. You can refer https://github.com/DerryHub/BEVFormer_tensorrt/tree/main/TensorRT#multi-scale-deformable-attention to use it.

thank for reply , i have readed this md, my doubt is when i export bevformer_tiny.pth for mmdeploy plugin onnx , i don't see the plugin op of MultiScale deformable attention , which should export failed ,and the ops of trt in mmdeploy 0.10.0 dont have the plugin of MultiScale deformable attention yet , but this onnx convert to trt successful

**Comment by reverse-2020** [comment]
> MultiScaleDeformableAttnTRT(2) support half(half2)/int8 while the mmdeploy plugins don't support. You can refer https://github.com/DerryHub/BEVFormer_tensorrt/tree/main/TensorRT#multi-scale-deformable-attention to use it.

Deformable attention can be split into several grid_sample operators, is that right?

**Comment by DerryHub** [comment]
> > MultiScaleDeformableAttnTRT(2) support half(half2)/int8 while the mmdeploy plugins don't support. You can refer https://github.com/DerryHub/BEVFormer_tensorrt/tree/main/TensorRT#multi-scale-deformable-attention to use it.
> 
> Deformable attention can be split into several grid_sample operators, is that right?

Yes, you are right.

**Comment by reverse-2020** [comment]
> > > MultiScaleDeformableAttnTRT(2) support half(half2)/int8 while the mmdeploy plugins don't support. You can refer https://github.com/DerryHub/BEVFormer_tensorrt/tree/main/TensorRT#multi-scale-deformable-attention to use it.
> > 
> > 
> > Deformable attention can be split into several grid_sample operators, is that right?
> 
> Yes, you are right.

okay, I see

**Comment by admyxs** [comment]
> > > MultiScaleDeformableAttnTRT(2) support half(half2)/int8 while the mmdeploy plugins don't support. You can refer https://github.com/DerryHub/BEVFormer_tensorrt/tree/main/TensorRT#multi-scale-deformable-attention to use it.
> > 
> > 
> > Deformable attention can be split into several grid_sample operators, is that right?
> 
> Yes, you are right.

thank for your great repo

I want to know how you do to make Deformable attention split into several grid_sample operators,

or MMDeploy help us to do this?
