### ISSUE TITLE
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:     1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

### ISSUE THREAD

**Issue by chaojiyu** [DerryHub/BEVFormer_tensorrt#7]
Hi Derry,

I got an error when I try to run scripts **samples/bevformer/base/onnx2trt.sh** and **samples/bevformer/plugin/base/onnx2trt_fp16.sh** to transport ONNX to TRT model. The error message is:
```
File "/home/tianyu/BEVFormer_tensorrt/./det2trt/convert/onnx2tensorrt.py", line 60, in build_engine
    engine = runtime.deserialize_cuda_engine(plan)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

```
I will really appreciate it if you can give me some support!

Thank you

**Comment by DerryHub** [comment]
Please provide the complete log file.

**Comment by chaojiyu** [comment]
> 
hi, here is the complete error message.

```
[01/15/2023-11:48:14] [TRT] [E] 10: [optimizer.cpp::computeCosts::3728] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Reshape_3290 + Reshape_3680 + Unsqueeze_3761 + Unsqueeze_3763 + Unsqueeze_3765...Reshape_3834]}.)
[01/15/2023-11:48:14] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
Traceback (most recent call last):
  File "tools/onnx2trt.py", line 61, in <module>
    main()
  File "tools/onnx2trt.py", line 50, in main
    build_engine(
  File "/home/tianyu/BEVFormer_tensorrt/./det2trt/convert/onnx2tensorrt.py", line 60, in build_engine
    engine = runtime.deserialize_cuda_engine(plan)
TypeError: deserialize_cuda_engine(): incompatible function arguments. The following argument types are supported:
    1. (self: tensorrt.tensorrt.Runtime, serialized_engine: buffer) -> tensorrt.tensorrt.ICudaEngine

Invoked with: <tensorrt.tensorrt.Runtime object at 0x7f667c740930>, None
```

**Comment by DerryHub** [comment]
Could you save the complete log to a file and upload it?

**Comment by chaojiyu** [comment]
> Could you save the complete log to a file and upload it?
I ran it again, and this time it worked. I guess previous error had something to do with cuda memory. Thank you very much for your help.

**Comment by Tanzichang** [comment]
Have you solved the problem? I just encountered the same problem.

**Comment by chaojiyu** [comment]
> Have you solved the problem? I just encountered the same problem.

I think the problem was caused by a lack of CUDA memory. After I shut down the other programs that took up CUDA memory, the code ran successfully without making any changes.

**Comment by Tanzichang** [comment]
> changes

Thanks for your reply. I have tried to shut down other programs and left enough GPU memory, but this error still exists. It seems that my problem is not caused by the insufficient GPU memory. Do you have any other ideas?
