### ISSUE TITLE
error: no instance of overloaded function "nvcuda::wmma::load_matrix_sync"

### ISSUE THREAD

**Issue by santoshcoder23** [DerryHub/BEVFormer_tensorrt#70]
getting 
_error: no instance of overloaded function "nvcuda::wmma::load_matrix_sync" matches the argument list_

while trying to run  _make -j$(nproc)_   at _BEVFormer_tensorrt/TensorRT/build_  in docker

**Comment by DerryHub** [comment]
what's your cuda version and gpu?

**Comment by santoshcoder23** [comment]
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+

**Comment by DerryHub** [comment]
Are you sure your gpu support Tensor Core? What's you gpu sm version?

**Comment by santoshcoder23** [comment]
Tesla V100.  Not sure how to get SM version.

**Comment by DerryHub** [comment]
The Tesla V100 don't support Tensor Core. You can back to the version to reinstall: https://github.com/DerryHub/BEVFormer_tensorrt/commit/dd136855b0e83aed9275f0a3cdc217b1498f305c

**Comment by nandubeigu** [comment]
> The Tesla V100 don't support Tensor Core. You can back to the version to reinstall: [dd13685](https://github.com/DerryHub/BEVFormer_tensorrt/commit/dd136855b0e83aed9275f0a3cdc217b1498f305c)

我也遇到了相同的问题，作者的意思是回退tensorrt版本？麻烦作者详细说明
