### ISSUE TITLE
Can't find BEVFormer_ptq_max model

### ISSUE THREAD

**Issue by Oh-Cest-la-vie** [DerryHub/BEVFormer_tensorrt#72]
Hi, thanks for your great work.
If you can tell me where I can download **bevformer_r101_dcn_24ep_ptq_max.pth** for convert to ONNX and engine of qdq model ?

**Comment by DerryHub** [comment]
You can get the pth by samples/bevformer/base/quant_max_ptq.sh

**Comment by Oh-Cest-la-vie** [comment]
Yes, I got it, thanks for your reply !
