### ISSUE TITLE
missing template specialization for type<__half> of function template "ms_deformable_im2col_cuda"

### ISSUE THREAD

**Issue by hygxy** [DerryHub/BEVFormer_tensorrt#9]
Is [here](https://github.com/DerryHub/BEVFormer_tensorrt/blob/main/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu#L379) missing the implementation for function template ```template void ms_deformable_im2col_cuda<__half>```declared [here](https://github.com/DerryHub/BEVFormer_tensorrt/blob/main/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu#L411)? or is it not necessary?

**Comment by DerryHub** [comment]
https://github.com/DerryHub/BEVFormer_tensorrt/blob/186010684f8c648fad4d5d5881d6c9817408b940/TensorRT/plugin/multi_scale_deformable_attn/multiScaleDeformableAttnKernel.cu#L358-L378

This function includes \<float> and <__half>.
